services:
  account:
    image: "siddhant9960/account-service:0.1"
    container_name: account-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
  loan:
    image: "siddhant9960/loan-service:0.1"
    container_name: loan-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
  card:
    image: "siddhant9960/card-service:0.1"
    container_name: card-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m