services:

  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  config:
    image: "siddhant9960/config-server:1.0"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  account:
    image: "siddhant9960/account-service:1.0"
    container_name: account-ms
    ports:
      - "8080:8080"
    depends_on:
      config:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "account"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loan:
    image: "siddhant9960/loan-service:1.0"
    container_name: loan-ms
    ports:
      - "8090:8090"
    depends_on:
      config:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loan"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  card:
    image: "siddhant9960/card-service:1.0"
    container_name: card-ms
    ports:
      - "9000:9000"
    depends_on:
      config:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "card"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  easyBank:
    driver: "bridge"