services:

  accountdb:
    container_name: accountdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  carddb:
    container_name: carddb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: carddb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loandb:
    container_name: loaddb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loandb
    extends:
      file: common-config.yml
      service: microservice-db-config

  config:
    image: "siddhant9960/config-server:1.0"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eureka:
    image: "siddhant9960/eureka-server:1.0"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"

  account:
    image: "siddhant9960/account-service:1.0"
    container_name: account-ms
    ports:
      - "8080:8080"
    depends_on:
      config:
        condition: service_healthy
      accountdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "account"
      SPRING_DATASOURCE_URL: jdbc:mysql://accountdb:3306/accountdb
    extends:
      file: common-config.yml
      service: microservice-eureka-config


  loan:
    image: "siddhant9960/loan-service:1.0"
    container_name: loan-ms
    ports:
      - "8090:8090"
    depends_on:
      config:
        condition: service_healthy
      loandb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loan"
      SPRING_DATASOURCE_URL: jdbc:mysql://loandb:3306/loandb
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  card:
    image: "siddhant9960/card-service:1.0"
    container_name: card-ms
    ports:
      - "9000:9000"
    depends_on:
      config:
        condition: service_healthy
      carddb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "card"
      SPRING_DATASOURCE_URL: jdbc:mysql://carddb:3306/carddb
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  easyBank:
    driver: "bridge"